### PR TITLE
add -ll to log full listener

### PR DESCRIPTION
**Pull request by elpie89**
added option to display the complete result of the max listener using the
native logger of user preferred ide/editor

tested with pycharm

### CODE REVIEW

**Comment by elpie89** [comment]
Hi Jeff, looking on the behaviour of the openlog command  I saw that actually, the command itself delete the old file and create a new one every time the command is called.
Practically every time we will run a command from the MXSPyCOM with the -f argument a new file will be created/overwritten

Also, the closelog command ensure only the last MXSPyCOMcommands are registered and avoid the log to store commands executed manually in the listener by the user
The only case that a log file is open and the size of the file increase is when MXSPyCOM
run the command openLog and than do not run the closeLog (i don't think this could happen)

We could eventually delete the file before MXSPyCOM return ,but I think it is a good idea to keep the log accessible from outside.
If you do not agree I will add the "delete log " right before the return statements

**Comment by JeffHanna** [comment]
Hi.

I'm sorry for the delay in responding. Between some Memorial Day weekend
plans and a few family issues that cropped up I've not been as attentive to
this as I should've been.

If openLog( ) is self maintaining and won't bloat a user's storage, great!
Let's go with that, then. I agree with your idea to not forcibly clean up
the log file if that is not necessary. Having that data available to aid in
debugging would be a benefit.


Jeff

**Comment by elpie89** [comment]
no problem Jeff.
I'm glad to help the community

**Review by unforgiven211981 — COMMENTED** [review]
Good

**Pull request merged**
